reorganized and renamed stuff to increase consistency, etc. All works

diff --git a/dataExchange/runEb b/dataExchange/runEb
--- a/dataExchange/runEb
+++ b/dataExchange/runEb
@@ -1,23 +1,3 @@
-node loadEbData.js --school --forReal -- dataFiles/eb/schoolSetup/school.eb
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-node loadEbData.js --gradeLevel --forReal dataFiles/eb/schoolSetup/gradeLevel.eb
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-node loadEbData.js --gradeLevelSchool --forReal dataFiles/eb/schoolSetup/gradeLevelSchool.eb
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
 
 node loadEbData.js --term --forReal -- dataFiles/eb/schoolSetup/term.eb
 		if [ $? -eq 1 ]
@@ -25,14 +5,31 @@ node loadEbData.js --term --forReal -- dataFiles/eb/schoolSetup/term.eb
 			echo "found error";
 			exit 1;
 		fi
-
-node loadEbData.js --termSchool --forReal -- dataFiles/eb/schoolSetup/termSchool.eb
+node loadEbData.js --gradeLevel --forReal dataFiles/eb/schoolSetup/gradeLevel.eb
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
 			exit 1;
 		fi
 
+node loadEbData.js --school --forReal -- dataFiles/eb/schoolSetup/school.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --gradeLevelSchool --forReal dataFiles/eb/schoolSetup/gradeLevelSchool.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --termSchool --forReal -- dataFiles/eb/schoolSetup/termSchool.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
 node loadEbData.js --schoolSetCurrentTerm --forReal -- dataFiles/eb/schoolSetup/school.eb
 		if [ $? -eq 1 ]
 		then
@@ -46,8 +43,32 @@ node loadEbData.js --student --forReal -- dataFiles/eb/peopleSetup/student.eb
 			echo "found error";
 			exit 1;
 		fi
-
 node loadEbData.js --teacher --forReal -- dataFiles/eb/peopleSetup/teacher.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+node loadEbData.js --objective  --forReal dataFiles/eb/objectiveSetup/objectives.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --assignGradeLevel  --forReal dataFiles/eb/objectiveSetup/gradeLevelAssignments.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --assignTerm  --forReal dataFiles/eb/objectiveSetup/termAssignments.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --assignSpecialty  --forReal dataFiles/eb/objectiveSetup/specialtyAssignments.eb
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
@@ -60,51 +81,17 @@ node loadEbData.js --homeroom --skipFirstLine --forReal -- dataFiles/eb/peopleSe
 			echo "found error";
 			exit 1;
 		fi
-
-node loadEbData.js --studentAssignment --forReal dataFiles/eb/peopleSetup/studentAssignment.eb
+node loadEbData.js --assignStudent --forReal dataFiles/eb/peopleSetup/assignStudent.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --assignTeacher --forReal dataFiles/eb/peopleSetup/assignTeacher.eb
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
 			exit 1;
 		fi
 
-node loadEbData.js --teacherAssignment --forReal dataFiles/eb/peopleSetup/teacherAssignment.eb
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-node loadEbData.js --objective  --forReal dataFiles/eb/objectiveSetup/objectives.eb
-
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-node loadEbData.js --assignGradeLevel  --forReal dataFiles/eb/objectiveSetup/gradeLevelAssignments.eb
-
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-node loadEbData.js --assignTerm  --forReal dataFiles/eb/objectiveSetup/termAssignments.eb
-
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-node loadEbData.js --assignSpecialty  --forReal dataFiles/eb/objectiveSetup/specialtyAssignments.eb
-
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-echo "Expressbook upload completed successfully"
+echo "EB upload completed successfully"
diff --git a/dataExchange/runUff b/dataExchange/runUff
--- a/dataExchange/runUff
+++ b/dataExchange/runUff
@@ -1,26 +1,10 @@
 
-node loadEbData.js --school --skipFirstLine --forReal dataFiles/uff/schoolSetup/school.uff
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-
 node loadEbData.js --term --skipFirstLine --forReal dataFiles/uff/schoolSetup/term.uff
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
 			exit 1;
 		fi
-
-node loadEbData.js --schoolSetCurrentTerm --forReal -- dataFiles/uff/schoolSetup/schoolSetCurrentTerm.uff
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
 node loadEbData.js --gradeLevel --skipFirstLine --forReal dataFiles/uff/schoolSetup/gradeLevel.uff
 		if [ $? -eq 1 ]
 		then
@@ -28,13 +12,28 @@ node loadEbData.js --gradeLevel --skipFirstLine --forReal dataFiles/uff/schoolSe
 			exit 1;
 		fi
 
-node loadEbData.js --student --skipFirstLine --forReal dataFiles/uff/peopleSetup/student.uff
+
+node loadEbData.js --school --skipFirstLine --forReal dataFiles/uff/schoolSetup/school.uff
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --schoolSetCurrentTerm --forReal -- dataFiles/uff/schoolSetup/schoolSetCurrentTerm.uff
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
 			exit 1;
 		fi
 
+
+
+node loadEbData.js --student --skipFirstLine --forReal dataFiles/uff/peopleSetup/student.uff
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
 node loadEbData.js --teacher --skipFirstLine --forReal -- dataFiles/uff/peopleSetup/teacher.uff
 		if [ $? -eq 1 ]
 		then
@@ -42,58 +41,51 @@ node loadEbData.js --teacher --skipFirstLine --forReal -- dataFiles/uff/peopleSe
 			exit 1;
 		fi
 
+
+node loadEbData.js --objective --forReal dataFiles/uff/objectiveSetup/objectives.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --assignGradeLevel --forReal dataFiles/uff/objectiveSetup/gradeLevelAssignments.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --assignTerm --forReal dataFiles/uff/objectiveSetup/termAssignments.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+node loadEbData.js --assignSpecialty --forReal dataFiles/uff/objectiveSetup/specialtyAssignments.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+
+
 node loadEbData.js --homeroom --skipFirstLine --forReal -- dataFiles/uff/peopleSetup/homeroom.uff
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
 			exit 1;
 		fi
-
-node loadEbData.js --studentAssignment --skipFirstLine --forReal dataFiles/uff/studentAssignment.uff
+node loadEbData.js --assignStudent --skipFirstLine --forReal dataFiles/uff/peopleSetup/assignStudent.uff
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
 			exit 1;
 		fi
-
-node loadEbData.js --teacherAssignment --skipFirstLine --forReal dataFiles/uff/teacherAssignment.uff
+node loadEbData.js --assignTeacher --skipFirstLine --forReal dataFiles/uff/peopleSetup/assignTeacher.uff
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
 			exit 1;
 		fi
-
-node loadEbData.js --objective --forReal dataFiles/uff/objectiveSetup/objectives.eb
-
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-node loadEbData.js --assignGradeLevel --forReal dataFiles/uff/objectiveSetup/gradeLevelAssignments.eb
-
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-node loadEbData.js --assignTerm --forReal dataFiles/uff/objectiveSetup/termAssignments.eb
-
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
-node loadEbData.js --assignSpecialty --forReal dataFiles/uff/objectiveSetup/specialtyAssignments.eb
-
-		if [ $? -eq 1 ]
-		then
-			echo "found error";
-			exit 1;
-		fi
-
 
 echo "UFF upload completed successfully"
