assignSpecialty and assignTerm work. Added LocalId to Specialty and MarkScale. Added LocalId data init to Specialty in sql and .ods

diff --git a/processCommonCore/runEb b/processCommonCore/runEb
--- a/processCommonCore/runEb
+++ b/processCommonCore/runEb
@@ -61,14 +61,46 @@ node loadEbData.js --homeroom --skipFirstLine --forReal -- dataFiles/eb/peopleSe
 			exit 1;
 		fi
 
-node loadEbData.js --studentAssignment --forReal dataFiles/eb/studentAssignment.eb
+node loadEbData.js --studentAssignment --forReal dataFiles/eb/peopleSetup/studentAssignment.eb
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
 			exit 1;
 		fi
 
-node loadEbData.js --teacherAssignment --forReal dataFiles/eb/teacherAssignment.eb
+node loadEbData.js --teacherAssignment --forReal dataFiles/eb/peopleSetup/teacherAssignment.eb
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+node loadEbData.js --objective  --forReal dataFiles/eb/objectiveSetup/objectives.eb
+
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+node loadEbData.js --assignGradeLevel  --forReal dataFiles/eb/objectiveSetup/gradeLevelAssignments.eb
+
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+node loadEbData.js --assignTerm  --forReal dataFiles/eb/objectiveSetup/termAssignments.eb
+
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+node loadEbData.js --assignSpecialty  --forReal dataFiles/eb/objectiveSetup/specialtyAssignments.eb
+
 		if [ $? -eq 1 ]
 		then
 			echo "found error";
diff --git a/processCommonCore/runUff b/processCommonCore/runUff
--- a/processCommonCore/runUff
+++ b/processCommonCore/runUff
@@ -63,4 +63,37 @@ node loadEbData.js --teacherAssignment --skipFirstLine --forReal dataFiles/uff/t
 			exit 1;
 		fi
 
+node loadEbData.js --objective --forReal dataFiles/uff/objectiveSetup/objectives.eb
+
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+node loadEbData.js --assignGradeLevel --forReal dataFiles/uff/objectiveSetup/gradeLevelAssignments.eb
+
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+node loadEbData.js --assignTerm --forReal dataFiles/uff/objectiveSetup/termAssignments.eb
+
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+node loadEbData.js --assignSpecialty --forReal dataFiles/uff/objectiveSetup/specialtyAssignments.eb
+
+		if [ $? -eq 1 ]
+		then
+			echo "found error";
+			exit 1;
+		fi
+
+
 echo "UFF upload completed successfully"
